Makefile

Just nitpicking on the makefile, but with changes I think are necessary. :)
Regenerate YAML Go bundle only if necessary.
Clean it when `make clean`.
Depend on that `bundle.go` file when building.
cc @leogr 
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>

Improvements to the makefile

---

.gitignore
Makefile
cmd/root.go
cmd/run.go
docs/event-generator.md
docs/event-generator_run.md
go.mod
go.sum
tools/docgen/docgen.go

Meant to be merged after a rebase on top of the masters (after #1; I'll do when you'll merge it).
It introduces a little standard tool to automatically generate Markdown documentation for the CLI commands.
It also provides a flag (not a viper one this time) to generate docs for a Hugo website. This way we can easily call it like so in the future and include/update the event-generator documentation in any Hugo website at build time.
Finally, it introduces a `make docs` command to generate markdown documentation for the GitHub repo and provides a first version of the docs.

Docs generation

---

cmd/root.go
cmd/run.go
docs/event-generator.md
docs/event-generator_list.md
docs/event-generator_run.md
pkg/runner/runner.go

> /kind bug
> /kind tests
/kind feature
/area commands
/area pkg
> /area events
This PR implements the `--loop` option for the run command and SIGTERM/SIGINT signals handling for graceful shutdown.
Fixes #6 
```release-note
new(cmd): add `--loop` option to run command
update(cmd): sleep time default to 1s
```

new(cmd): add `--loop` option to run command

---

cmd/run.go
go.mod
go.sum

By default including client-go doesn't import all auth types, so there
are some implementations we won't be able to auth to. This pulls in all
the auth types at the cost of a larger binary.
/kind cleanup
/area commands
This adds more auth functionality to kubernetes clusters. I needed oidc authentication to communicate with my managed IBM Cloud Kubernetes cluster.
None
I *think* the main consequence of this is that the binary will be bigger. I honestly …

chore(events/k8saudit): pull in all k8s auth modes

---

Makefile

/kind bug
> /kind tests
> /area pkg
> /area events
This PR fixes `make test` when no bundle file (`events/k8saudit/yaml_loader.go`) is present.
The [issue](https://app.circleci.com/pipelines/github/falcosecurity/event-generator/1/workflows/65dd6a96-857c-4b2e-98b9-f7a214c778e6/jobs/1/parallel-runs/0/steps/0-102) showed up on CircleCI.
Fixes #
**Does this PR introduce a user-facing …

fix(Makefile): correct `make test` when no bundle

---

Dockerfile

This directory needs to exist for the write below rpm database action to
succeed
/kind cleanup
/area pkg
This directory needs to exist for the write below rpm database action to
succeed
None
No
```release-note
NONE
```

Add /var/lib/rpm

---

cmd/run.go
events/interfaces.go
events/syscall/non_sudo_setuid.go
pkg/runner/helper.go
pkg/runner/runner.go

/kind bug
> /kind tests
/area pkg
/area events
Running `syscall.NonSudoSetuid` affects the execution of subsequent actions. We need to isolate it in a child process.
Fixes #21 
```release-note
fix(events/syscall): NonSudoSetuid affected subsequent actions
```

fix(syscall): isolate NonSudoSetuid in a child process

---

.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
/kind cleanup
NONE
Follow-up from https://github.com/falcosecurity/test-infra/pull/154
NONE
```release-note
NONE
```

update(.github): remove release-note block

---

Dockerfile

/kind bug
The `build-base` meta-package is now needed by the builder image since some dependencies make use of `cgo`.
Since https://github.com/falcosecurity/event-generator/pull/48, trying to build the docker image without `build-base` fails with the following error:
```
...
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exec: "gcc": executable file not found in $PATH
make: *** [Makefile:30: event-generator] Error 2
```
To reproduce the issue, try `make image` from the master branch.
As a bonus, this PR also upgrades the base image version from alpine 3.13 to 3.14 as well.
/milestone v0.7.0
**Special notes for your …

fix: add `build-base` to builder image

---

go.mod
go.sum

/kind cleanup
This bumps the version of `client-go` to v0.5.0.

update(go.mod): bump client-go to version 0.5.0

---

.circleci/config.yml
.goreleaser.yml
Dockerfile

Resolves #57.
The following file has been modified :
Modify Dockerfile,.goreleaser and .circleci/config files to build and push the image for both amd64 and arm64 platforms.
Signed-off-by: odidev odidev@puresoftware.com

Release docker images for arm64

---

.goreleaser.yml
Makefile

/kind bug
> /kind tests
> /area pkg
> /area events
Basically, on arm64 the docker image is segfaulting as soon as event-generator starts, at the link phase:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000c131a8 in frame_dummy ()
#2  0x0000ffff8b6ee780 in ?? () from /lib/ld-musl-aarch64.so.1
#3  0x0000fffff8c3b328 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
This is due to …

fix(build): force-set the `pie` build mode to allow arm64 images built on alpine to work

---

README.md

> /kind bug
/kind cleanup
> /kind tests
> /area pkg
> /area events
The default grpc unix socket path was changed in 0.33.0 from /var/run/falco.sock to /run/falco/falco.sock and there were still some stale references to the old socket name.
Fixes #

docs(README.md): update grpc output socket name

---

events/syscall/remove_bulk_data_from_disk.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for the default stable rule "Remove Bulk Data from Disk"  which is very important to test because sometimes bulk data removal can be done with the intention to destroy data, possibly interrupting availability to systems.
Fixes #

Added event for default stable rule "Remove Bulk Data from Disk"

---

events/README.md

> /kind bug
> /kind tests
> /area pkg
/area events
Fixes #

docs(events/README.md): update conventions

---

events/syscall/change_namespace_privileges_via_unshare.go
events/syscall/change_namespace_privillege_using_unshare.go

adding an event for stable rule `change_namespace_privillege_using_unshare`
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Fixes #123 

adding an event on change_namespace_privilleges_using_unshare

---

events/syscall/decoding_payload_in_container.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
this is an syscall event which will trigger `Decoding payload in container` rule
Fixes #115 

adding event on triggering rule `decoding payload in container`

---

events/syscall/kubernetes_client_tool_launched_in_container.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Kubernetes Client Tool Launched in Container" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco-sandbox_rules.yaml#L1519C9-L1519C53)
Fixes #168 

Added an event for default rule "Kubernetes Client Tool Launched in Container"

---

events/syscall/delete_or_rename_shell_history.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
this event will trigger rule Delete_or_rename_shell_history
Fixes #105 

adding an event of deleting bash history

---

events/syscall/modify_shell_configuration_file.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
this PR trigger rule `modify shell configuration file`
Fixes #107 

adding an event for modifying shell configuration file

---

events/syscall/read_ssh_information.go
events/syscall/utils_linux.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added event for default rule "Read SSH Information"
Fixes #

Added event for default rule "Read SSH Information"

---

events/syscall/adding_ssh_keys_to_authorized_keys.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Adding ssh keys to authorized_keys"
Fixes #116 

Added an event for default rule "Adding ssh keys to authorized_keys"

---

events/syscall/detect_crypto_miners_using_the_stratum_protocol.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Detect crypto miners using the Stratum protocol" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco-sandbox_rules.yaml#L1482C9-L1482C56)
Fixes #172 

Added an event for default rule "Detect crypto miners using the Stratum protocol"

---

events/syscall/find_aws_credentials.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default stable rule "Find AWS Credentials"
Fixes #

Added an event for default stable rule "Find AWS Credentials"

---

events/syscall/read_shell_configuration_file.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule read shell configuration file. 
Fixes #

Added an event for default rule read shell configuration file

---

events/syscall/launch_package_management_process_in_container.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Launch Package Management Process In Container" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco-incubating_rules.yaml#L935)
Fixes #178 

Added an event for default rule "Launch Package Management Process In Container"

---

events/syscall/unprivileged_delegation_of_page_faults_handling_to_a_userspace_process.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Unprivileged Delegation of Page Faults Handling to a Userspace Process" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco-sandbox_rules.yaml#L1630C9-L1630C79)
Fixes #170 

Added an event for default rule "Unprivileged Delegation of Page Faults Handling to a Userspace Process"

---

events/syscall/ptrace_attached_to_process.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default stable rule "PTRACE attached to process" mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco_rules.yaml#L1099C9-L1099C35)
Fixes #131 

Added an event for default stable rule "PTRACE attached to process"

---

events/syscall/container_drift_detected_chmod.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Container drift detected using chmod" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco-sandbox_rules.yaml#L1545)
Fixes #181 

Added an event for default rule "Container drift detected using chmod"

---

events/syscall/set_setuid_or_set_setgid_bit.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Set Setuid or Setgid bit" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco-incubating_rules.yaml#L1045C9-L1045C33)
Fixes #162 

Added an event for default rule "Set Setuid or Setgid bit"

---

events/syscall/launch_remote_file_copy_tool_in_container.go
events/syscall/launch_remote_file_copy_tools_in_container.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
this PR based on rule which helps with data  exfiltration.
Fixes #175 

adding event on launch remote file copy tool in container

---

events/syscall/execution_from_dev_shm.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default stable rule "Execution from /dev/shm"
Fixes #

Added an event for default stable rule "Execution from /dev/shm"

---

events/syscall/container_drift_detected_open_create.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Container Drift Detected (open+create)" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco-sandbox_rules.yaml#L1569)
Fixes #181 

Added an event for default rule "Container Drift Detected (open+create)"

---

events/syscall/drop_and_execute_new_binary_in_container.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default stable rule 'Drop and execute new binary in container' as mentioned [here](https://github.com/falcosecurity/rules/blob/88a40c8d9c9af7985998689e9847f60a2a5de898/rules/falco_rules.yaml#L1174)
Fixes #195 

Added an event for default stable rule 'Drop and execute new binary in container'

---

events/interfaces.go
events/syscall/db_program_spawned_process.go
events/syscall/non_sudo_setuid.go
events/syscall/read_sensitive_file_trusted_after_startup.go
events/syscall/run_shell_untrusted.go
events/syscall/system_procs_network_activity.go
events/syscall/user_mgmt_binaries.go
pkg/runner/helper.go

… to copy or symlink the binary
> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
The change introduced by this PR can be used to trigger rules that are based on proc.exepath rather than proc.name for better detection purposes.
Fixes #

new(pkg/runner/helper): added SpawnAsWithSymlink and modified SpawnAs to make a copy

---

events/README.md
events/syscall/change_namespace_privileges_via_unshare.go
events/syscall/contact_cloud_metadata_service_from_container.go
events/syscall/container_drift_detected_chmod.go
events/syscall/container_drift_detected_open_create.go
events/syscall/debugfs_launched_in_privilleged_container.go
events/syscall/decoding_payload_in_container.go
events/syscall/drop_and_execute_new_binary_in_container.go
events/syscall/kubernetes_client_tool_launched_in_container.go
events/syscall/launch_package_management_process_in_container.go
events/syscall/launch_remote_file_copy_tools_in_container.go
events/syscall/launch_remote_file_copy_tools_inside_container.go
events/syscall/launch_suspicious_network_tool_in_container.go
events/syscall/launch_suspicious_network_tool_on_host.go
events/syscall/netcat_remote_code_execution_in_container.go
events/syscall/program_run_with_disallowed_http_proxy_env.go

/kind bug
> /kind tests
> /area pkg
/area events
Fixes #201 

Fix: Use events.ErrSkipped with a proper Reason when skipping an actions

---

events/syscall/read_environment_variable_fromm_proc.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
this event trigger rule `read environment variable from /proc file`
Fixes #111 

adding an event on reading environment variable from /proc files

---

events/syscall/disallowed_ssh_connection_non_standard_port.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
this triggers rule `disallowed ssh connection non standard port`
Fixes #142 

adding an event for disallowed_ssh_connection_non_standard_port

---

events/syscall/execution_from_dev_shm.go

@FedeDP @leogr As os.Mkdir("/dev/shm") returns error as /dev not exists so instead we should use os.Mkdir("/dev") which just create /dev. 
And  /dev/shm created in the next lines of code
/kind bug
> /kind tests
> /area pkg
/area events
Fixes #

Fix: In ExecutionFromDevShm we should use os.Mkdir("/dev") instead if os.Mkdir("/dev/shm")

---

events/syscall/packet_socket_created_in_container.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
This event triggers stable rule `packet_socket_created_in_container`
Fixes #134 

adding an event on packet_socket_created_in_container

---

events/helper/outbound_connection.go
events/syscall/interpreted_procs_outbound_network_activity.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
this triggers rule `interpreted procs outbound network activity`
Fixes #152 

adding an event on `interpreted procs outbound network activity`

---

events/syscall/modify_container_entrypoint.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
this event must to have as it try to create environment of `Container Breakout Exploit (CVE-2019-5736)`
Fixes #186 

adding an event on modify container entrypoint

---

events/helper/inbound_connection.go
events/syscall/interpreted_inbound_network_activity.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
this PR triggers rule `interpreted procs inbound network activity`
Fixes #151 

adding an event on `interpreted procs inbound network activity`

---

events/syscall/mount_launched_in_privileged_container.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Fixes #204 

adding event for this rule `mount launched in privileged container`

---

cmd/common.go
cmd/declarative.go
cmd/run.go
cmd/test.go
events/exampleyamlfile.yml
pkg/declarative/helpers.go
pkg/declarative/runner.go
pkg/declarative/yamltypes.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
> /area events
This PR is to add support for testing falco rules using declarative YAML files in event-generator. The implementation idea is [here](https://hackmd.io/@aldolck/r1o9yU170) 
Part of GSoC 2024 project "Falco: Upgrading event-generator and automating Falco performance testing"
https://github.com/falcosecurity/evolution/issues/362
cc @jasondellaluce @alacuku

Feature: Add support for testing falco rules using declarative YAML files in event-generator

---

events/syscall/polkit_local_privilege_escalation_vulnerability.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for defalult rule "Polkit Local Privilege Escalation Vulnerability (CVE-2021-4034)" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco-sandbox_rules.yaml#L1645C9-L1645C72)
Fixes #149 

Added an event for defalult rule "Polkit Local Privilege Escalation Vulnerability (CVE-2021-4034)"

---

events/syscall/detect_release_agent_file.go

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Fixes #193 

Added an event for default stable rule Detect release_agent File Container Escapes

---

events/exampleyamlfile.yml
pkg/declarative/helpers.go
pkg/declarative/host.go
pkg/declarative/yamltypes.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
Part of GSoC 2024 task
Fixes #
cc @alacuku @jasondellaluce

Feat: Add helper functions for making syscalls

---

cmd/declarativetest.go
cmd/test.go
events/exampleyamlfile.yml

> /kind bug
> /kind tests
/kind feature
> /area pkg
> /area events
It adds a declarative sub-command for the test command. Which takes yaml file path and parses it and runs the tests similar to the run declarative functionality which we added earlier and it also tests whether a falco rule is triggered or not by connecting to the running falco instance through grpc api.
Fixes #
@alacuku @jasondellaluce

Feature: Added declarative subcommand for test command

---

events/syscall/disallowed_ssh_connection_non_standard_port.go

/kind bug
/area events
on some systems, the syscall.DisallowedSSHConnectionNonStandardPort event does not trigger due to too short timeout of 1s, so we're increasing it to 5s
Fixes #221 
//cc: @leogr i was able to reproduce the issue on lima and arm64 mac, but have not seen it on minikube or "vanilla" ubuntu kvm vm on linux x86/amd64 before: `signal: killed` comes from the context timeout that was apparently too short in this case
```
$ falco --version
Fri Sep 20 19:09:58 2024: Falco version: 0.38.2 (aarch64)
Fri Sep 20 19:09:58 2024: Falco initialized with configuration files:
Fri Sep 20 …
```

increase timeout for syscall.DisallowedSSHConnectionNonStandardPort

---

Makefile

/kind bug
> /kind tests
/area commands
> /area pkg
> /area events
On a Mac M1, trying to cross-compile for linux/amd64 fails when trying to run the `file-bundler` tool with the wrong arch:
```
$ GOOS=linux GOARCH=amd64 make
rm -f -R event-generator
rm -f events/k8saudit/yaml/bundle.go
rm -f -R event-generator evtgen-docgen
go run ./tools/file-bundler/ events/k8saudit/yaml
fork/exec /var/folders/t_/1ckd5szj47g4pcb36j5zgmnr0000gp/T/go-build630400765/b001/exe/file-bundler: exec format error
make: *** …
```

build: fix cross-compilation

---

go.mod
go.sum
pkg/test/loader/loader.go
pkg/test/resource/clientserver/clientserver.go
pkg/test/resource/clientserver/doc.go
pkg/test/resource/doc.go
pkg/test/resource/resource.go
pkg/test/step/syscall/socket/socket.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR introduces the concept of test resource and the `clientServer` test resource.
A test resource abstracts a resource the user wants to use in a test, hiding the implementation details and letting the user focus only on the action that will trigger the Falco rule.
The `clientServer` test resource sets up a client and a server, and enables their communication by tuning the underlying network infrastructure. The user can specify `udp4`, `udp6`, `tcp4`, …

feat(decl/resources): introduce test resource concept and clientServer resource

---

pkg/test/loader/loader.go
pkg/test/resource/builder/builder.go
pkg/test/resource/builder/doc.go
pkg/test/resource/fd/directory/directory.go
pkg/test/resource/fd/directory/doc.go
pkg/test/resource/fd/epoll/doc.go
pkg/test/resource/fd/epoll/epoll.go
pkg/test/resource/fd/event/doc.go
pkg/test/resource/fd/event/event.go
pkg/test/resource/fd/file/doc.go
pkg/test/resource/fd/file/file.go
pkg/test/resource/fd/inotify/doc.go
pkg/test/resource/fd/inotify/inotify.go
pkg/test/resource/fd/mem/doc.go
pkg/test/resource/fd/mem/mem.go
pkg/test/resource/fd/pipe/doc.go
pkg/test/resource/fd/pipe/pipe.go
pkg/test/resource/fd/signal/doc.go
pkg/test/resource/fd/signal/signal.go
pkg/test/resource/resource.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR adds the `fd` test resource, the test resource builder and fixes some minor issues related to YAML specs validation. The `fd` test resource is a resource that lets the user declaratively create one file descriptor (or more, in case of `pipe`) . The user must specify the fd type using the `subtype` YAML field. The following `subtype`s have been introduced:
- `file`
- `directory`
- `pipe`
- `event`
- `signalfd`
- `eventpoll`
- `inotify`
- `memfd` …

feat(decl/resources): adds fd test resource and test resource builder

---

pkg/test/builder/builder.go
pkg/test/builder/doc.go
pkg/test/doc.go
pkg/test/script/shell/doc.go
pkg/test/script/shell/shell.go
pkg/test/test.go
pkg/test/test/doc.go
pkg/test/test/test.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR adds support for running declarative tests specification through the `Test` abstraction. The provided test implementation runs the following logical steps:
1. Run "before" script
2. Create test resources
3. Run test steps
4. Run test steps cleanup procedures
5. Destroy test resource
6. Run "after" script
If running "before" script or creating test resources produces an error, the test execution is aborted, as these logical steps considered prerequisites …

feat(decl/tests): add declarative test support

---

pkg/test/builder/builder.go
pkg/test/loader/loader.go
pkg/test/resource/builder/builder.go
pkg/test/resource/clientserver/clientserver.go
pkg/test/runner/builder/builder.go
pkg/test/runner/builder/doc.go
pkg/test/runner/doc.go
pkg/test/runner/host/doc.go
pkg/test/runner/host/host.go
pkg/test/runner/runner.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR adds the definition runner and runner builder, and provides implementations for them. Specifically, it introduces the `host` runner, which can be used to run a test on the host system. The host runner supports the generation of the process chain, as specified by the user in the test description. In order to enable communication of the test configuration from a parent process to a child process (spawned during the creation of the process chain), this PR …

feat(decl/runners): add host runner and test serialization support

---

cmd/declarative/declarative.go
cmd/declarative/doc.go
cmd/declarative/run/doc.go
cmd/declarative/run/run.go
cmd/root.go
go.mod
go.sum
pkg/log/doc.go
pkg/log/log.go
pkg/test/loader/doc.go
pkg/test/loader/loader.go
pkg/test/runner/builder/builder.go
pkg/test/runner/host/host.go
pkg/test/runner/runner.go
pkg/test/step/syscall/base/parse.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR introduces the `declarative` commands namespace and the `declarative run` subcommand to enable users to run tests via a YAML description of them.
It also introduces a new `log` package, leveraging `logr` and the `zap` logger, that is going to replace the actual `logrus` logger in the future. However, for the moment, it lets `logrus` and `logr` coexists until is decided to completely replace `logrus` with `logr`. 
Finally, it enable support for providing …

feat(decl): add CLI support to run declarative tests

---

pkg/test/step/syscall/base/base.go

/kind bug
> /kind tests
/area pkg
> /area events
The issue can be reproduced with the following test:
```
tests:
- rule: DirectoryTraversalMonitoredFileRead
name: test2
runner: HostRunner
before: "echo Hi"
steps:
- type: syscall
name: open
syscall: open
args:
pathname: "/etc/../etc/../etc/shadow"
flags: 0
mode: 0644
after: "echo Bye"
```
It was crashing with:
```
panic: reflect: call of reflect.Value.SetInt on uint32 Value
```
After this fix it runs successfully:
```
2024-11-10T23:22:23.483+0100	info	root …
```

fix(decl): use SetUint for open_mode uint32 field

---

pkg/test/loader/loader.go
pkg/test/script/shell/shell.go

/kind bug
> /kind tests
/area pkg
> /area events
This PR fixes the `SIGUSR1` signal handling for shell scripts by correctly handling the exit code set by the signal (138). The first instruction after the blocking `wait` now verifies the returned exit code and clears its value if it matches the one set by the signal. Moreover, this PR fixes a potential nil pointer dereference in test context validation and conditionally disable shell script execution when both "before" and "after" scripts are not provided by …

fix(decl): potential nil ptr deref and shell script SIGUSR handling

---

pkg/test/field/field.go
pkg/test/loader/loader.go
pkg/test/step/syscall/base/base.go
pkg/test/step/syscall/base/parse.go
pkg/test/step/syscall/connect/connect.go
pkg/test/step/syscall/dup/dup.go
pkg/test/step/syscall/dup2/dup2.go
pkg/test/step/syscall/dup2/dup2_arm64.go
pkg/test/step/syscall/dup3/dup3.go
pkg/test/step/syscall/finitmodule/finitmodule.go
pkg/test/step/syscall/initmodule/initmodule.go
pkg/test/step/syscall/kill/kill.go
pkg/test/step/syscall/link/link.go
pkg/test/step/syscall/link/link_arm64.go
pkg/test/step/syscall/linkat/linkat.go
pkg/test/step/syscall/open/open.go
pkg/test/step/syscall/open/open_arm64.go
pkg/test/step/syscall/openat/openat.go
pkg/test/step/syscall/openat2/openat2.go
pkg/test/step/syscall/read/read.go
pkg/test/step/syscall/sendto/sendto.go
pkg/test/step/syscall/socket/socket.go
pkg/test/step/syscall/symlink/symlink.go
pkg/test/step/syscall/symlink/symlink_arm64.go
pkg/test/step/syscall/symlinkat/symlinkat.go
pkg/test/step/syscall/syscall.go
pkg/test/step/syscall/write/write.go

/kind bug
> /kind tests
/area pkg
> /area events
This PR fixes the system call arguments are handled, starting from the decoding phase up to the system call step arguments settings. Specifically, arguments are now parsed as `map[string]interface{}` (instead of `map[string]string`): this enables field binding at arbitrary level and decouples architecture inner layers from tests input encoding.
Moreover, this PR replaces `interface{}` with the equivalent but more explicit `any`.
**Which issue(s) this PR …

fix(decl): fix syscalls argument parsing and cleanup logic 

---

pkg/test/script/shell/shell.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR replaces sh shell with bash in declarative tests "before" and "after" scripts.
Fixes #250 

feat(decl/scripts): replace sh with bash

---

cmd/declarative/test/test.go
pkg/test/tester/tester/tester.go

/kind bug
> /kind tests
/area commands
> /area pkg
> /area events
This PR fixes the `test` command termination handling upon failures. Specifically, now the command waits for goroutines termination before terminating the process.
Fixes #254 

fix(decl/cmd/test): wait for goroutines termination upon failures

---

cmd/declarative/test/test.go
pkg/test/loader/loader.go
pkg/test/loader/schema/jsonschemas/expectedOutcome.schema.json
pkg/test/loader/schema/jsonschemas/test.schema.json
pkg/test/tester/tester.go
pkg/test/tester/tester/tester.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR conditionally makes the `rule` and `expectedOutcome` fields optional in the YAML tests description.
If the user run a test through the `declarative run` command or, equivalently, the `declarative test --skip-outcome-verification` command, these  fields are ignored.
If the user run a test through `declarative test` command, the `rule` field is mandatory, and an empty `expectedOutcome` matches any outcome resulting from the application of the test …

feat(decl): make `rule` and `expectedOutcome` conditionally optional

---

.github/workflows/ci.yaml

chore(ci): switch to github provided arm64 runners.

---

pkg/test/runner/host/host.go

/kind bug
> /kind tests
/area pkg
> /area events
This PR fixes host runner delegation logic.
Fixes #

fix(decl/runners): fix host runner delegation logic

---

pkg/test/loader/loader.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR relaxes field binding syntax by allowing any number of spaces to be placed in the positions specified by the following expression (spaces are allowed where the `<space>` placeholder is present): `"<space>${<space><fieldBindingExpr><space}<space>"`
Fixes #

feat(decl/loader): allow spaces in field binding syntax

---

cmd/declarative/test/test.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR switches from decremental to incremental backoff in report retrieval and move report retrieval and printing logic out of `runTestSuite`.
Fixes #

feat(decl/cmd/test): switch to incremental backoff in report retrieval

---

cmd/declarative/test/test.go
pkg/test/tester/tester.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR restructures the `cmd/test` code to change the way test results are collected and printed. Test reports are now collected by test suite and printed all together. Moreover, a failure in the execution of a single test doesn't prevent anymore the execution of the other tests, as the test is simply accounted as failed.
Fixes #252 

feat(decl/cmd/test): groups test reports by test suite 

---

pkg/process/builder/builder.go
pkg/process/process.go

> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR introduces the capability to automatically the directory hierarchy for a specified simulated executable path in process chain if it doesn't exist. The created hierarchy is automatically deleted upon process resources release.
Fixes #

feat(decl/proc-chain): create proc exe dir hierarchy if not exist

---

pkg/test/step/syscall/read/read.go
pkg/test/step/syscall/write/write.go

/kind bug
> /kind tests
/area pkg
> /area events
This PR updates, upon successful execution, `read` and `write` syscall steps buffers and lengths arguments to their new value. This is especially important when buffers are created on the fly with the specified length, or when lengths default to the buffers length. This is required in order to enable subsequent steps to correctly see the updated values.
Fixes #

fix(suite/step/syscalls): align `read` and `write` step args after run
