falcosecurity/event-generator

.dockerignore, Dockerfile, Makefile, README.md, deployment/event-generator.yaml, deployment/run-as-job.yaml
/kind feature
/area events
Fixes #5
Edited by @leogr : #8 will not be completely fixed by this PR, the goal is to implement a command.
```release-note
new: add `falcosecurity/event-generator` container image
```
=> Create docker image and deployment file

cmd/list.go, cmd/root.go, docs/event-generator.md, docs/event-generator_list.md
> /kind bug
> /kind tests
/kind feature
/area commands
> /area pkg
> /area events
So users can list available actions
Fixes #
```release-note
new(cmd): command to list available actions
```
=> new(cmd): command to list available actions

.circleci/config.yml, .goreleaser.yml, Makefile
> /kind bug
> /kind tests
> /area pkg
> /area events
Automated releases!
Fixes #7 
```release-note
NONE
```
=> CI and automated release

README.md, deployment/event-generator.yaml
> /kind bug
> /kind tests
> /area pkg
> /area events
This PR refines the README.md and accordingly updates the related k8s deployment file.
Fixes #16 
```release-note
update(deployment): run with `--loop` when using k8s deployment
```
=> Refinements 

Dockerfile
/kind bug
> /kind tests
> /area pkg
> /area events
To fix the following error when run in a container:
```
ERRO action error                                  action=helper.RunShell as=httpd error="exec: \"bash\": executable file not found in $PATH"
```
Fixes #
```release-note
fix(Dockerfile): add bash required by helper.RunShell
```
=> fix(Dockerfile): add bash required by helper.RunShell

events/k8saudit/yaml_loader.go
/kind bug
> /kind tests
> /area pkg
/area events
Fixes #22 
```release-note
fix(events/k8saudit): correct misplaced reader when loading YAML
```
=> fix(events/k8saudit): correct misplaced reader when loading YAML

events/README.md
/kind cleanup
/area events
Minor typo fix
NONE
Fixes #
```release-note
NONE
```
=> fix(docs): very small typo

events/syscall/schedule_cron_jobs.go
Note that we disable cronjob events in the default falco rules so those
will need to be turned on to see this event. Grep for
'consider_all_cron_jobs' in falco_rules.yaml
/kind feature
/area events
Adds event for modifying the cronjobs on the host
NONE
Fixes #
```release-note
new(events/syscall): schedule cron jobs
```
=> new(events/syscall): add cronjob event

README.md
Just to update the events list.
Fixes #
```release-note
NONE
```
=> docs(README.md): update events list

cmd/bench.go, events/registry.go, release.md
Add documentation for releasing and fixes some typos in code comments.
Fixes #35 
=> Releasing docs and correct typos

cmd/bench.go, cmd/list.go, cmd/run.go, docs/event-generator_bench.md, docs/event-generator_run.md, docs/event-generator_test.md, go.mod, go.sum, pkg/counter/counter.go, pkg/counter/stats.go
> /kind bug
/kind cleanup
> /kind tests
/kind feature
/area commands
/area pkg
> /area events
Just small improvements for the `bench` command and new fine-tuned defaults for `--sleep` and `--round-duration` flags.
Fixes #
=> Improved bechmark strategy

docs/event-generator.md, docs/event-generator_bench.md, docs/event-generator_list.md, docs/event-generator_run.md, docs/event-generator_test.md
> /kind tests
> /area pkg
> /area events
Fixes #
=> docs: update commands documentation

release.md
> /kind bug
> /kind tests
> /area pkg
> /area events
Fixes #
=> docs(RELEASE.md): correct slack channel URL

go.mod
Signed-off-by: Thomas Spear <tspear@conquestcyber.com> 
/kind bug
> /kind tests
> /area pkg
> /area events
Fixes CVE-2021-3121
Fixes #51
=> Upgrade protobuf to fix CVE

.circleci/config.yml
/kind bug
> /kind tests
> /area pkg
> /area events
Fixes #53
This is required to unblock the `v0.6.2` release.
=> build(.circleci): upgrade docker version for releasing

.circleci/config.yml
> /kind bug
/kind cleanup
> /kind tests
/area commands
> /area pkg
> /area events
Increases CI timeout.
Fixes #
=> update: set a 60m timeout for both circleCI and goreleaser.

.circleci/config.yml
> /kind bug
/kind cleanup
> /kind tests
/area commands
> /area pkg
> /area events
See https://support.circleci.com/hc/en-us/articles/360058095471-How-To-Use-Docker-Buildx-in-Remote-Docker-
Fixes #
=> update: since we are forcing docker version 20.x, buildx is already provided by it

.circleci/config.yml
/kind bug
> /kind tests
/area commands
> /area pkg
> /area events
Basically, reverts #62  as it isn't  working.
Fixes #
=> chore: restore old buildx install.

.goreleaser.yml
> /kind bug
/kind cleanup
> /kind tests
> /area pkg
> /area events
Fixes #
=> update(build): drop i386 support.

OWNERS
> /kind bug
> /kind tests
> /area pkg
> /area events
Fixes #
=> update(owners): add Federico Di Pierro as owner.

.circleci/config.yml
> /kind bug
> /kind tests
/kind feature
> /area pkg
> /area events
Fixes #
=> new(ci): added arm64 ci.

cmd/common.go, docs/event-generator_bench.md, docs/event-generator_test.md
/kind bug
/area commands
This PR fixes the `grpc` unix path
=> fix: grpc unix path

.circleci/config.yml
/kind cleanup
* Use cimg/go instead of deprecated circleci/golang images.
* moreover, properly install goreleaser from deb repository
* Finally, bump buildx version
Fixes #
=> update(circleci): multiple ci updates

.github/PULL_REQUEST_TEMPLATE.md, README.md, events/README.md
> /kind bug
/kind cleanup
> /kind tests
> /area pkg
> /area events
Fixes #
=> docs(events): correct URL to `main` branch

README.md
=> chore(readme): add an arch badge.

.github/workflows/ci.yaml
=> new(ci): use actuated.dev arm64 node.

README.md, cmd/bench.go, cmd/list.go, docs/event-generator_bench.md, docs/event-generator_list.md, docs/event-generator_run.md, docs/event-generator_test.md, events/README.md, events/k8saudit/yaml_disabled.go, events/syscall/change_thread_namespace.go, events/syscall/create_files_below_dev.go, events/syscall/create_symlink_over_sensitive_files.go, events/syscall/db_program_spawned_process.go, events/syscall/directory_traversal_monitored_file_read.go, events/syscall/mkdir_binary_dirs.go, events/syscall/modify_binary_dirs.go, events/syscall/non_sudo_setuid.go, events/syscall/search_private_keys_or_passwords.go, events/syscall/system_procs_network_activity.go, events/syscall/user_mgmt_binaries.go, events/syscall/write_below_binary_dir.go, events/syscall/write_below_etc.go, events/syscall/write_below_rpm_database.go, pkg/runner/helper.go, pkg/runner/runner.go, tools/file-bundler/main.go
> /kind bug
/kind cleanup
> /kind tests
/kind feature
/area commands
/area pkg
/area events
Fixes #
=> Update for Falco 0.37 - event-generator 0.11

events/README.md
> /kind bug
> /kind tests
> /area pkg
/area events
Corrected a typo in README.md file in events folder
**Which issue(s) this PR fixes:**
Fixes #
=> Corrected a typo in README.md file

events/syscall/write_below_root.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added event for default rule write_below_root
Fixes #
=> Added event for default rule "Write below root"

events/syscall/create_hardlink_over_sensitive_files.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
We need to create hard link over sensitive file that would trigger the create hard link over sensitive files Rule, This PR adds a way to create a hard link over sensitive files 
Fixes #92 
=> falco: create hardlink over sensitive file event added

events/syscall/create_hidden_file_or_directory.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for the default rule create hidden file or directory as mentioned [here](https://github.com/falcosecurity/rules/blob/172d2c283f9b432b5dc55239a4003dd19f237182/rules/falco-sandbox_rules.yaml#L1354)
Fixes #
=> Added event for the default rule create hidden file or directory

README.md
> /kind bug
> /kind tests
> /area pkg
> /area events
Fix broken link by replacing it with valid url
Fixes #
=> Fix broken link by replacing it with valid url

events/syscall/launch_remote_file_copy_tools_inside_container.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Launch Ingress Remote File Copy Tools in Container" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco-incubating_rules.yaml#L1168)
Fixes #164 
=> Added an event for default rule "Launch Ingress Remote File Copy Tools in Container"

events/syscall/program_run_with_disallowed_http_proxy_env.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Program run with disallowed http proxy env"
Fixes #
=> Added an event for default rule "Program run with disallowed http proxy env"

events/syscall/netcat_remote_code_execution_in_container.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
it is based on RCE prevention rule.
Fixes #180 
=> adding event on netcat rce in container

events/syscall/unexpected_udp_traffic.go
added event on triggering rule `unexpected UDP traffic`
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Fixes #119 
=> adding event on unexpected_udp_traffic

events/interfaces.go, events/syscall/fileless_execution_via_memfd_create.go, pkg/runner/helper.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default stable rule "Fileless execution via memfd_create" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco_rules.yaml#L1233) whose priority is `critical`
Fixes #137 
=> Added an event for default stable rule "Fileless execution via memfd_create"

events/syscall/ptrace_anti_debug_attempt.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default stable rule "PTRACE anti-debug attempt"
Fixes #132 
=> Added an event for default stable rule "PTRACE anti-debug attempt"

events/helper/combined_server_client.go, events/syscall/java_process_class_file_download.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
This is `critical` labeled rule, hence we must have event on this
Fixes #114 
=> adding an event on `java process class file download`

events/syscall/contact_ec2_instance_metadata_from_container.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
this event triggers rule `contact_ec2_instance_metadata_from_container`
Fixes #147 
=> adding event on triggering this rule contact_ec2_instance_metadata_from_container

events/syscall/sudo_potential_privilege_escalaton.go
> /kind bug
> /kind tests
/kind feature
> /area pkg
/area events
Added an event for default rule "Sudo Potential Privilege Escalation" as mentioned [here](https://github.com/falcosecurity/rules/blob/fbf0a4e8ce6b56a9c5ec4e6c4abadfaf14c9786b/rules/falco-sandbox_rules.yaml#L1612C9-L1612C44)
Fixes #150 
=> Added an event for default rule "Sudo Potential Privilege Escalation"

events/syscall/java_process_class_file_download.go, events/syscall/potential_local_privilege_escalation_via_environment_variables_misuse.go
/kind bug
> /kind tests
> /area pkg
/area events
See https://github.com/falcosecurity/event-generator/pull/220#issuecomment-2363239838
Fixes #
cc @prezha @alacuku @FedeDP
=> Disable not stable rules

README.md, docs/event-generator_bench.md
> /kind bug
> /kind tests
> /area pkg
> /area events
Fixes #
=> Docs: update for v0.12

.dockerignore
Use white-list approach to exclude unneeded but currently included files and directories.
> /kind bug
/kind cleanup
> /kind tests
/kind feature
> /area pkg
> /area events
This PR allows docker to exclude unneeded but currently included files and directories. Contextually, it replaces the black-list approach with a white-list approach: this allows to explicitly include only the needed items.
Fixes #
=> chore(dockerignore): use white-list approach

.github/workflows/lint.yaml, .golangci.yml, Makefile, cmd/bench.go, cmd/common.go, cmd/config_options.go, cmd/list.go, cmd/root.go, cmd/run.go, cmd/test.go, events/syscall/read_ssh_information.go, events/syscall/schedule_cron_jobs.go, events/syscall/unprivileged_delegation_of_page_faults_handling_to_a_userspace_process.go, events/syscall/utils_linux.go, pkg/counter/counter.go, pkg/runner/helper.go, pkg/runner/plugin.go, pkg/runner/runner.go, pkg/tester/tester.go, test/events/init_test.go, tools/docgen/docgen.go
> /kind bug
> /kind tests
> /area pkg
> /area events
This PR adds `golanci-lint` to the repository and applies it to the files.
Fixes #
=> add linter

.github/workflows/ci.yaml
> /kind bug
/kind cleanup
> /kind tests
/area pkg
> /area events
This PR changes the arm64 runner in the CI.
Fixes #
=> update(ci): use arm64 CNCF runners for GH actions

pkg/test/tester/reportencoder/textencoder/textencoder.go
/kind bug
> /kind tests
/area pkg
> /area events
As per PR title, add new line for better summary of failed tests
Fixes #
=> fix: add missing new line for better visualization of failed tests

pkg/test/loader/loader.go
/kind bug
> /kind tests
/area pkg
> /area events
This PR fixes the algorithm to check uniqueness among steps/resources names.
Fixes #
=> fix(decl/loader): fix steps/resources name uniqueness enforcement

cmd/declarative/test/test.go
> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR moves context from loggers name to loggers attributes.
Fixes #
=> feat(decl/cmd/test): move context from logger name to attributes

cmd/declarative/config/config.go, cmd/declarative/test/test.go, pkg/test/runner/host/host.go, pkg/test/runner/runner.go, pkg/test/suite/suite.go
> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR introduces the possibility to specify multiple description files as a comma-separated list to `--description-file` flag. It is also possible to specify the flag multiple time, each time with different lists of description files.
Similarly, it is also possible to specify one or more directory paths using the `--description-dir` flag. All (and only) `.yaml` files inside each of the provided directory paths are loaded. The specified directories are not …
=> feat(decl/cmd/test): allow multiple description files and introduce `--description-dir` flag

cmd/declarative/test/test.go
> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR let test and run commands honor context cancellation during test report generation.
Fixes #
=> feat(decl/cmd/test): honor ctx cancellation in report generation

cmd/declarative/test/test.go, pkg/test/suite/suite.go
> /kind bug
/kind cleanup
> /kind tests
/area pkg
> /area events
This PR moves no-rule check logic from test command to suite loader.
Fixes #
=> refactor(decl/suite): move no-rule check logic in suite loader

cmd/declarative/test/test.go
> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR gives a name to the alert retriever.
Fixes #
=> feat(decl/cmd/test): give a name to alert retriever logger

pkg/capability/capability.go, pkg/process/builder/builder.go
> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR moves the function setting capabilities on a file to the `capability` package. This is done in order to isolate dependency on  `"kernel.org/pub/linux/libs/security/libcap/cap"`
Fixes #
=> refactor(decl/caps): move func setting capabilities to capability pkg

pkg/osutil/doc.go, pkg/osutil/osutil.go, pkg/process/builder/builder.go, pkg/test/resource/fd/directory/directory.go, pkg/test/resource/fd/file/file.go
> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR adds the capability to create the requested directory hierarchies (if they don't it) to the `file` and `directory` `fd` resources.
Fixes #
=> feat(decl/fd): create dir hierarchy if not exist

cmd/suite/config/doc.go, cmd/suite/suite.go
> /kind bug
> /kind tests
/area commands
> /area pkg
> /area events
Follow-up to https://github.com/falcosecurity/event-generator/pull/283#pullrequestreview-2645136133
Fixes #
=> docs(cmd): improve `suite` command description

OWNERS
> /kind bug
> /kind tests
> /area pkg
> /area events
Considering the huge [contribution](https://github.com/falcosecurity/event-generator/graphs/contributors) @ekoops made to this repository in the last months and as per our [maintainer guideline](https://github.com/falcosecurity/evolution/blob/main/MAINTAINERS_GUIDELINES.md#onboarding-a-reviewer), I'm proposing he become a [reviewer](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#reviewers) of this repository.
**Which issue(s) this PR …
=> docs(OWNERS): add ekoops as reviewer

cmd/suite/test/test.go, pkg/test/suite/reportencoder/textencoder/textencoder.go, pkg/test/tester/tester.go
> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR allows report encoders to add information regarding the current test case to the output.
Fixes #
=> feat(suite/cmd/test): output test cases information in report encoding

.github/workflows/publish-main.yaml, .goreleaser.main.yml
/kind bug
> /kind tests
> /area pkg
> /area events
Fixes #
=> fix: enable goreleaser push for `main`

.github/workflows/publish-main.yaml
/kind bug
> /kind tests
> /area pkg
> /area events
Fixes #
=> fix(.github/publish-main.yaml): revert unnecessary override

.github/workflows/publish-main.yaml
/kind bug
> /kind tests
> /area pkg
> /area events
Fixes #
=> update(.github): switch to multi platform build in one step

pkg/test/step/syscall/base/base.go, pkg/test/step/syscall/connect/connect.go, pkg/test/step/syscall/dup/dup.go, pkg/test/step/syscall/dup2/dup2.go, pkg/test/step/syscall/dup3/dup3.go, pkg/test/step/syscall/finitmodule/finitmodule.go, pkg/test/step/syscall/initmodule/initmodule.go, pkg/test/step/syscall/kill/kill.go, pkg/test/step/syscall/link/link.go, pkg/test/step/syscall/linkat/linkat.go, pkg/test/step/syscall/open/open.go, pkg/test/step/syscall/openat/openat.go, pkg/test/step/syscall/openat2/openat2.go, pkg/test/step/syscall/read/read.go, pkg/test/step/syscall/sendto/sendto.go, pkg/test/step/syscall/socket/socket.go, pkg/test/step/syscall/symlink/symlink.go, pkg/test/step/syscall/symlinkat/symlinkat.go, pkg/test/step/syscall/write/write.go
> /kind bug
> /kind tests
/kind feature
/area pkg
> /area events
This PR introduces mutually-exclusive-arguments, one-required-argument and required-together-arguments constraints. In particular:
- mutually-exclusive-arguments constraint allows to mandate the user to specify a value for at most one of a set of arguments
- one-required-argument constraint allows to mandate the user to specify a value for at least one of a set of arguments
- required-together-arguments constraints allows to mandate the user to specify a value …
=> feat(suite/step/syscalls): add arguments constraints support
